spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init.mode: always
---
logging:
  level:
    org:
      springframework:
        orm.jpa: INFO
        transaction: INFO
        transaction.interceptor: TRACE
        orm.jpa.JpaTransactionManager: DEBUG
---
spring:
  config:
    activate:
      on-profile: ci, test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test
