CREATE TABLE IF NOT EXISTS USERS
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS REQUESTS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    requestor   INTEGER,
    created     TIMESTAMP,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    is_available BOOLEAN,
    owner_id     INTEGER REFERENCES USERS (id),
    requests_id  INTEGER REFERENCES REQUESTS (id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS BOOKINGS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date timestamp                               NOT NULL,
    end_date   timestamp                               NOT NULL,
    item_id    INTEGER REFERENCES ITEMS (id),
    booker_id  INTEGER REFERENCES USERS (id),
    status     VARCHAR(255),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text_comment VARCHAR(512)                            NOT NULL,
    item_id      INTEGER REFERENCES ITEMS (id),
    author_id    INTEGER REFERENCES USERS (id),
    created      timestamp                               NOT NULL
);
